### ISSUE TITLE
Cannot buy Spawneggs

### ISSUE THREAD

**Issue by MonoAdrian23** [llamadevelopment/LlamaShop#2]
I have register new Spawnegg Ids to buy.
For example, 852:0 is Pig Spawnegg
A player buy this and get this egg without reduce money after rejoin.
Old Ids of Spawneggs doenst work.

**Comment by Proxma3838** [comment]
There is no official support for PowerNukkit. Try and use nukkit and tell us if the problem still occurs.

**Comment by MonoAdrian23** [comment]
Why are you closing this issue without knowing my Software?
I use Nukkit!


Proxma ***@***.***> schrieb am So., 4. Apr. 2021, 17:30:

**Comment by MonoAdrian23** [comment]
You closing my issue without knowing my Software!!????
Sorry but, I use Nukkit.
I search for another Dev.
Too stupid!

**Comment by Proxma3838** [comment]
In the past you've used PowerNukkit, so we thought you're still using it. We will look into it asap.
No reason to insult us. Calm down.
