### ISSUE TITLE
Please add Powernukkit Support

### ISSUE THREAD

**Issue by PocketMiner92** [llamadevelopment/LlamaShop#4]
Many 1.16 Items with negative IDS doenst work.
Please add Support for it.

**Comment by JustinLLDV** [comment]
This is not a PowerNukkit plugin.

**Comment by PocketMiner92** [comment]
This is why i have asked for Support lol.

**Comment by JustinLLDV** [comment]
Yeah, and we won't add support for it. Because we can't. The only thing we modify is the speed of the furnace, that has nothing to do with the new items or anything else.
